### PR TITLE
JsonableBehavior to not decode again

### PR DESCRIPTION
**Pull request by ayman-alkom**
It seems that the behavior decode again in association queries, so I added some conditions

### CODE REVIEW

**Comment by dereuromark** [comment]
Is there a test for it? :)

**Comment by ayman-alkom** [comment]
I 'm very bad with tests, it will take a lot of discussion to achieve it, so I suggest you to don't relay on me. ;)

you even can discard this PR and make your changes in other commit

**Comment by dereuromark** [comment]
Do you have some example code I could test with?

**Comment by ayman-alkom** [comment]
OK, I have two tables, `connections` and `statements`:
```sql
CREATE TABLE IF NOT EXISTS `connections` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(63) NOT NULL,
  `driver` varchar(15) NOT NULL,
  `con_str` text NOT NULL, -- JSON FIELD IS HERE
  `app_id` smallint(5) unsigned NOT NULL,
  `db_schema` longblob,
  `is_valid` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `status` smallint(4) NOT NULL DEFAULT '-1',
  `tables_count` mediumint(8) unsigned DEFAULT '0',
  `last_scan` datetime DEFAULT NULL,
  `user_id` varchar(36) NOT NULL,
  `created` date NOT NULL,
  `modified` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8  ;
```
```sql
CREATE TABLE IF NOT EXISTS `statements` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(127) CHARACTER SET utf8 NOT NULL,
  `type` smallint(5) unsigned NOT NULL,
  `query` text,
  `metadata` text,
  `created_by` char(36) DEFAULT NULL,
  `app_id` int(10) unsigned NOT NULL,
  `is_public` tinyint(1) NOT NULL,
  `description` text,
  `columns` text,
  `created` date NOT NULL,
  `modified` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1  ;
```

The problem occurs when I call $statements->find()->contains([Connections]);

**Comment by dereuromark** [comment]
Is this fixed with https://github.com/dereuromark/cakephp-tools/commit/351a1798a4588ab00ec917a9b275af105f62c85e ?

**Comment by ayman-alkom** [comment]
yes it is, thanks

**Pull request closed without merging**
