### PR TITLE
Fixing issue where ints are casted to strings

### LINKED ISSUE #231: Common Component casts int to strings
See https://github.com/FriendsOfCake/cakephp-upload/pull/506#discussion_r261884166 for further details.

### PR DESCRIPTION
**Pull request by challgren**
Fixes #231

### CODE REVIEW

**Comment by dereuromark** [comment]
That trim should only happen on true strings. We should exclude all other types too

**Comment by challgren** [comment]
Ok I'll revise to just return anything that isn't a string

**Comment by challgren** [comment]
See https://github.com/FriendsOfCake/cakephp-upload/pull/506

**Comment by challgren** [comment]
FYI Codecov in your travis build script isn't working correctly. Can't find the coverage file.

**Pull request merged**
