### PR TITLE
Avoid namespace conflicts

### PR DESCRIPTION
**Pull request by Ali1**

### CODE REVIEW

**Comment by dereuromark** [comment]
How do u get a conflict?

**Comment by Ali1** [comment]
No runtime problems, just an IDE warning that there are 2 AppControllers as
my app namespace is App\....

This is just a suggestion - I’m still learning best practices so not sure
if how you have done is ok or not.

Thanks
-- 
Sent from my iPhone

**Comment by dereuromark** [comment]
If you use stable releases those wont be there anyway, but none the less I can try to finish this up.

**Comment by dereuromark** [comment]
Solved in master

**Pull request closed without merging**
